[package]
name = "api"
version = "0.1.0"

[dependencies]
log = "^0.4"
rocket = "^0.4"
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
slog = "^2"
slog-async = "^2"
slog-json = "^2"
slog-scope = "^4"
slog-stdlog = "^3"
