[package]
name = "api"
version = "0.1.0"
autobins = false

[dependencies]
lambda_runtime = "0.1"
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
log = "^0.4"
json_logger = "^0.0.2"
simple_logger = "^1"

[[bin]]
name = "bootstrap"
path = "src/main.rs"
