steps:
  - name: 'python:3.7-stretch'
    entrypoint: "bash"
    args: ["parse.sh"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./site", "gs://our_first_big_thing.howhardwoulditbe.com"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["acl", "ch", "-u", "AllUsers:R", "gs://our_first_big_thing.howhardwoulditbe.com/*"]
