version: 2.1
commands:
  init_deploy:
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - build-python-{{ checksum "Pipfile.txt" }}
            - build-python-
      - run: |
          python3 -m venv venv
          . ./venv/bin/activate
          pip install -r Pipfile.txt
      - save_cache:
          key: build-python-{{ checksum "Pipfile.txt" }}
          paths:
            - ./venv/
jobs:

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
              docker build -t app/$CIRCLE_SHA1 -t \
              registry.heroku.com/our-first-big-thing/web .
      - run:
          name: Push image
          command: |
              docker login --username=_ --password=$HEROKU_AUTH_TOKEN_JANUARY_2019 registry.heroku.com
              docker push registry.heroku.com/our-first-big-thing/web
      - run:
          name: Release image
          command: |
              image_id=`docker inspect app/$CIRCLE_SHA1 --format={{.Id}}`
              echo "Releasing image $image_id"
              # Update this if we add a non-web worker
              # https://devcenter.heroku.com/articles/container-registry-and-runtime#api
              curl -n -X PATCH https://api.heroku.com/apps/our-first-big-thing/formation \
              -d "{ \"updates\": [{\"type\": \"web\", \"docker_image\": \"$image_id\" }]}" \
              -H "Authorization: Bearer $HEROKU_AUTH_TOKEN_JANUARY_2019" \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases"

workflows:
  version: 2.1
  ci:
    jobs:
      # TODO(kyle): for now we deploy straight to staging always, because that's convenient
      # Later we can deploy production only on master
      - deploy
