version: 2.1
commands:
  init_deploy:
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - build-python-{{ checksum "Pipfile.txt" }}
            - build-python-
      - run: |
          python3 -m venv venv
          . ./venv/bin/activate
          pip install -r Pipfile.txt
      - save_cache:
          key: build-python-{{ checksum "Pipfile.txt" }}
          paths:
            - ./venv/

  deploy:
    parameters:
      app:
        type: string
    steps:
      - checkout
      - run:
          name: Build
          command: |
              docker build -t app/$CIRCLE_SHA1 -t \
              registry.heroku.com/<< parameters.app >>/web .
      - run:
          name: Push image
          command: |
              docker login --username=_ --password=$HEROKU_AUTH_TOKEN_JANUARY_2019 registry.heroku.com
              docker push registry.heroku.com/<< parameters.app >>/web
      - run:
          name: Release image
          command: |
              image_id=`docker inspect app/$CIRCLE_SHA1 --format={{.Id}}`
              echo "Releasing image $image_id"
              # Update this if we add a non-web worker
              # https://devcenter.heroku.com/articles/container-registry-and-runtime#api
              curl -n -X PATCH https://api.heroku.com/apps/<< parameters.app >>/formation \
              -d "{ \"updates\": [{\"type\": \"web\", \"docker_image\": \"$image_id\" }]}" \
              -H "Authorization: Bearer $HEROKU_AUTH_TOKEN_JANUARY_2019" \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases"

jobs:

  deploy-staging:
    machine: true
    steps:
      - deploy:
          app: our-first-big-thing

  deploy-production:
    machine: true
    steps:
      - deploy:
          app: turning-point-tales


workflows:
  version: 2.1
  ci:
    jobs:
      - deploy-staging
      - deploy-production:
          requires:
            - deploy-staging
          filters:
            branches:
              only:
                - master

