version: 2.1
commands:
  test-app:
    parameters:
      url:
        type: string
    steps:
      - checkout
      - run:
          name: Latest Chrome for Cypress
          command: |
              curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
              sudo dpkg -i google-chrome.deb
              sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
              rm google-chrome.deb
      - restore_cache:
          keys:
            - test-app-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          key: test-app-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.cache
      - run:
          name: Jest Tests
          command: |
            npm run jest test/
      - run:
          name: Cypress Tests
          command: |
            CYPRESS_BASE_URL=<< parameters.url >> npm run cy:run
  deploy:
    parameters:
      app:
        type: string
    steps:
      - checkout
      - run:
          name: Build
          command: |
              docker build -t app/$CIRCLE_SHA1 -t \
              registry.heroku.com/<< parameters.app >>/web .
      - run:
          name: Push image
          command: |
              docker login --username=_ --password=$HEROKU_AUTH_TOKEN_JANUARY_2019 registry.heroku.com
              docker push registry.heroku.com/<< parameters.app >>/web
      - run:
          name: Release image
          command: |
              image_id=`docker inspect app/$CIRCLE_SHA1 --format={{.Id}}`
              echo "Releasing image $image_id"
              # Update this if we add a non-web worker
              # https://devcenter.heroku.com/articles/container-registry-and-runtime#api
              curl -n -X PATCH https://api.heroku.com/apps/<< parameters.app >>/formation \
              -d "{ \"updates\": [{\"type\": \"web\", \"docker_image\": \"$image_id\" }]}" \
              -H "Authorization: Bearer $HEROKU_AUTH_TOKEN_JANUARY_2019" \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases"

jobs:
  pre-approval:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - run:
          name: Hello
          command: echo "I'm here so we can have a hold step!"

  deploy-staging:
    machine: true
    steps:
      - deploy:
          app: our-first-big-thing

  reset-staging:
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Seed
          command: CONNECTION_STRING="$STAGING_DATABASE_URL" npm run db:seed

  test-staging:
    machine: true
    steps:
      - test-app:
          url: https://ourfirstbigthing.howhardwoulditbe.com

  deploy-production:
    machine: true
    steps:
      - deploy:
          app: turning-point-tales

workflows:
  version: 2.1
  ci:
    jobs:
      - pre-approval
      - wait-for-dat-button-press:
          type: approval
      - reset-staging:
          requires:
            - wait-for-dat-button-press
      - deploy-staging:
          requires:
            - wait-for-dat-button-press
      - test-staging:
          requires:
            - deploy-staging
            - reset-staging
      - deploy-production:
          requires:
            - test-staging
          filters:
            branches:
              only:
                - master
