version: 2.1
commands:
  checkout_install:
    steps:
      - checkout
      - restore_cache:
          key: pip-cache-{{ checksum "Pipfile.txt" }}
      - run: |
          python3 -m venv venv
          . ./venv/bin/activate
          pip install -r Pipfile.txt
      - save_cache:
          key: pip-cache-{{ checksum "Pipfile.txt" }}
          paths:
            - ./venv

jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout_install

  deploy_test:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout_install
      - run: |
          . ./venv/bin/activate
          python3 -m awscli s3 sync site s3://test.howhardwoulditbe.com/$CIRCLE_BRANCH --delete

  deploy_prod:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout_install
      - run: |
          . ./venv/bin/activate
          python3 -m awscli s3 sync site s3://ourfirstbigthing.howhardwoulditbe.com/$CIRCLE_BRANCH --delete

workflows:
  version: 2.1
  ci:
    jobs:
      - build
      - deploy_test:
          requires:
            - build
      - deploy_prod:
          requires:
            - deploy_test
          filters:
            branches:
              only: master
