name: CD
on:
  push:
    branches:
      - master
    paths-ignore:
      - stories*
      - postgres*
      - test*
      - infrastructure*
      - cypress*
      - scripts*

jobs:
  jest:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 11.6
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache cache
        uses: actions/cache@v1
        with:
          path: ~/.cache # some cached files, cypress, are stored here
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-
      - run: npm install
      - run: npm run jest
  deploy-staging:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@master
      - name: login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN_JANUARY_2020 }}
        with:
          args: container:login
      - name: push
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN_JANUARY_2020 }}
        with:
          args: container:push -a our-first-big-thing web
      - name: release
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN_JANUARY_2020 }}
        with:
          args: container:release -a our-first-big-thing web
  reset-staging:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 11.6
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache cache
        uses: actions/cache@v1
        with:
          path: ~/.cache # some cached files, cypress, are stored here
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-
      - run: npm install
      - name: Seed
        run: CONNECTION_STRING="${{secrets.STAGING_DATABASE_URL}}" npm run db:seed
  staging-integration-test:
    needs: [reset-staging, deploy-staging]
    runs-on: ubuntu-16.04
    container: cypress/included:3.8.2
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 11.6
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        name: Cypress run
        with:
          browser: chrome
        env:
          CYPRESS_BASE_URL: https://ourfirstbigthing.howhardwoulditbe.com
  deploy-production:
    runs-on: ubuntu-16.04
    needs: [staging-integration-test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@master
      - name: login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN_JANUARY_2020 }}
        with:
          args: container:login
      - name: push
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN_JANUARY_2020 }}
        with:
          args: container:push -a turning-point-tales web
      - name: release
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_AUTH_TOKEN_JANUARY_2020 }}
        with:
          args: container:release -a turning-point-tales web
